# Generated by Django 2.2.10 on 2020-04-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm_type', models.CharField(choices=[('FLC', 'FLC'), ('FSC', 'FSC'), ('Crate', 'Crate'), ('other', 'Other')], default=0, max_length=250)),
                ('outer_length', models.IntegerField(blank=True, default=0, null=True)),
                ('outer_breadth', models.IntegerField(blank=True, default=0, null=True)),
                ('outer_height', models.IntegerField(blank=True, default=0, null=True)),
                ('inner_length', models.IntegerField(blank=True, default=0, null=True)),
                ('inner_breadth', models.IntegerField(blank=True, default=0, null=True)),
                ('inner_height', models.IntegerField(blank=True, default=0, null=True)),
                ('type_of_inserts', models.IntegerField(blank=True, default=0, null=True)),
                ('sep_sheet_perpm', models.IntegerField(blank=True, default=0, null=True)),
                ('ss_length', models.IntegerField(blank=True, default=0, null=True)),
                ('ss_breadth', models.IntegerField(blank=True, default=0, null=True)),
                ('ss_height', models.IntegerField(blank=True, default=0, null=True)),
                ('ss_type', models.IntegerField(blank=True, default=0, null=True)),
                ('ss_weight', models.IntegerField(blank=True, default=0, null=True)),
                ('ss_thickness', models.IntegerField(blank=True, default=0, null=True)),
                ('ss_gsm', models.IntegerField(blank=True, default=0, null=True)),
                ('total_pm_permonth', models.IntegerField(blank=True, default=0, null=True)),
                ('total_weight_capacity', models.IntegerField(blank=True, default=0, null=True)),
                ('remarks', models.CharField(blank=True, default=0, max_length=250, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_exam', models.IntegerField(default=None)),
                ('no_of_inserts_perit', models.IntegerField(blank=True, default=0, null=True)),
                ('insert_length', models.IntegerField(blank=True, default=0, null=True)),
                ('insert_breadth', models.IntegerField(blank=True, default=0, null=True)),
                ('insert_height', models.IntegerField(blank=True, default=0, null=True)),
                ('insert_type', models.IntegerField(blank=True, default=0, null=True)),
                ('insert_weight', models.IntegerField(blank=True, default=0, null=True)),
                ('insert_thickness', models.IntegerField(blank=True, default=0, null=True)),
                ('insert_gsm', models.IntegerField(blank=True, default=0, null=True)),
                ('parts_per_layer', models.IntegerField(blank=True, default=0, null=True)),
                ('pocket_length', models.IntegerField(blank=True, default=0, null=True)),
                ('pocket_breadth', models.IntegerField(blank=True, default=0, null=True)),
                ('pocket_height', models.IntegerField(blank=True, default=0, null=True)),
                ('matrix_detail', models.CharField(blank=True, default=0, max_length=250, null=True)),
            ],
        ),
    ]
